name: Branch CI (Snapshot)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      is_snapshot: true
      version_regex: "-SNAPSHOT$"   # Ensure the version ends with -SNAPSHOT
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}