name: Branch CI (Snapshot)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
          cache: maven

  call-build-and-deploy:
    uses: ./.github/workflows/build_and_deploy.yml@initial-work
    with:
      is_snapshot: true
      version_regex: "-SNAPSHOT$"   # Ensure the version ends with -SNAPSHOT
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
