name: Branch CI (Snapshot)

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Deploy SNAPSHOT
        run: ./mvnw --batch-mode -DskipTests -Darguments=-DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}