name: Main CI (Release)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-and-deploy:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      is_snapshot: false
      version_regex: "^[^\\s-]+$"  # Ensure the version does not contain -SNAPSHOT
