name: Pull Request CI (Snapshot)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml

  event_file:
    needs: build
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
